[app]
executors = 10
fs_repo_path = "./data"
send_path_executables = true

[server]
host = "127.0.0.1"
port.grpc = 32081
port.ssh = 32082
allow_unknown_hosts = false

[server.auth]
name = "agent-1"
generate_keys = true
key = "/etc/xdcs/keys/xdcs-agent"

[agent]
name = "Agent 1"

[system]
docker = "docker"
