[app]
executors = 10
local_port = 25254
fs_repo_path = "./data"
send_path_executables = true

[server]
host = "xdcs-server"
port.grpc = 8081
port.ssh = 8082

[server.auth]
name = "admin"
password = "admin"

[agent]
name = "Agent 1"

[system]
docker = "docker"
