version: "3.7"
services:
  xdcs-frontend:
    build:
      context: ./xdcs-frontend
      dockerfile: Dockerfile
    ports:
      - "31080:8080"
    volumes:
      - ./:/var/xdcs
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - xdcs-server

  xdcs-server:
    build:
      context: ./xdcs-server
    ports:
      - "32080:8080"
      - "32081:8081"
      - "32082:8082"
      - "32090:9990"
      - "32087:8787"
