version: "3.7"
services:
  xdcs-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - xdcs-server

  xdcs-frontend:
    build:
      context: ./xdcs-frontend
      dockerfile: Dockerfile
    ports:
      - "31080:8080"
    volumes:
      - ./:/var/xdcs
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - xdcs-server

  xdcs-server:
    build:
      context: ./xdcs-server
      dockerfile: Dockerfile
    ports:
      - "32080:8080"
      - "32081:8081"
      - "32082:8082"
      - "32090:9990"
      - "32087:8787"
    volumes:
      - xdcs-data:/opt/jboss/wildfly/xdcs
    depends_on:
      - xdcs-db
      - xdcs-ldap

  xdcs-db:
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_DB=xdcs
      - POSTGRES_USER=xdcs
      - POSTGRES_PASSWORD=xdcs
    volumes:
      - postgres-data:/var/lib/postgresql/data

  xdcs-db-admin:
    image: dpage/pgadmin4:4.16
    ports:
      - "34775:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  xdcs-ldap:
    image: osixia/openldap
    command: ["--copy-service"]
    volumes:
      - ./xdcs-server/dev/ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/ldap.ldif

  xdcs-ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "xdcs-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "36080:80"
    depends_on:
      - xdcs-ldap

volumes:
  postgres-data:
  xdcs-data:
