version: "3.7"
services:
  xdcs-frontend:
    build:
      context: ./xdcs-frontend
      dockerfile: Dockerfile
    ports:
      - "31080:8080"
    volumes:
      - ./:/var/xdcs
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - xdcs-server

  xdcs-server:
    build:
      context: ./xdcs-server
      dockerfile: Dockerfile
    ports:
      - "32080:8080"
      - "32081:8081"
      - "32082:8082"
      - "32090:9990"
      - "32087:8787"
    volumes:
      - xdcs-data:/opt/jboss/wildfly/xdcs
    depends_on:
      - xdcs-db

  xdcs-db:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_DB=xdcs
      - POSTGRES_USER=xdcs
      - POSTGRES_PASSWORD=xdcs
    volumes:
      - postgres-data:/var/lib/postgresql/data

  xdcs-db-admin:
    image: dpage/pgadmin4
    ports:
      - "34775:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  postgres-data:
  xdcs-data:
