version: "3.7"
services:
  xdcs-server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - XDCS_DB_JDBC_URL=jdbc:postgresql://localhost:5432/xdcs
    ports:
      - "32080:8080"
      - "32081:8081"
      - "32082:8082"
