version: "3.7"
services:
  xdcs-frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    ports:
      - "31080:8080"
    depends_on:
      - xdcs-server

  xdcs-server:
    build:
      dockerfile: Dockerfile.server
      context: .
    ports:
      - "32080:8080"
      - "32081:8081"
      - "32082:8082"
