version: "3.7"
services:
  xdcs-server:
    build:
      context: ./xdcs-server
      args:
        debug: "true"
    image: xdcs/xdcs-server
    ports:
      - "32080:8080"
      - "32090:9990"
      - "32087:8787"
