openapi: 3.0.0

info:
  title: XDCS REST API
  version: 1.0.0

paths:
  /example:
    get:
      operationId: get
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleDto'


components:
  schemas:
    ExampleDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        date:
          type: string
          format: 'date-time'
